-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-30 08:51:27 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL oo_schema_output.txt

--student id: 34091904
--student name: Nashmia Shakeel


DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     add_num        NUMBER (7)  NOT NULL , 
     add_street     VARCHAR2 (50)  NOT NULL , 
     add_street_num NUMBER (7)  NOT NULL , 
     add_town       VARCHAR2 (50)  NOT NULL , 
     add_postcode   NUMBER (10)  NOT NULL , 
     add_country    VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.add_num IS 'unique identifier for the address (surrogate key)' 
;

COMMENT ON COLUMN ADDRESS.add_street IS 'The stree at which the passenger currently lives ' 
;

COMMENT ON COLUMN ADDRESS.add_street_num IS 'the street number of the street where the passenger currently lives ' 
;

COMMENT ON COLUMN ADDRESS.add_town IS 'the name of the town where the passenger currently lives ' 
;

COMMENT ON COLUMN ADDRESS.add_postcode IS 'the postcode of the town where the passenger currently lives ' 
;

COMMENT ON COLUMN ADDRESS.add_country IS 'the country where the passenger currently lives' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( add_num ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_NK UNIQUE ( add_street , add_street_num , add_postcode , add_town , add_country ) ;

CREATE TABLE CABIN 
    ( 
     cabin_num      NUMBER (7)  NOT NULL , 
     cabin_capacity NUMBER (7)  NOT NULL , 
     cabin_class    CHAR (1)  NOT NULL , 
     ship_code      NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_class 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_num IS 'Unique Identifier for the Cabin ' 
;

COMMENT ON COLUMN CABIN.cabin_capacity IS 'Represents the cabin''s sleeping capacity ' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'cabin class represents the quaility of experience and services avaible for that particular cabin ( I for Interior, B for Balcony, O for Ocean View and S for Suite)' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'Unique identifier for the ship ' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_num, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (50) 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'Unique identifier for the country ' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'the name of the country of the port ' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id              NUMBER (7)  NOT NULL , 
     cruise_name            VARCHAR2 (50)  NOT NULL , 
     cruise_desc            VARCHAR2 (100)  NOT NULL , 
     cruise_date_time       DATE  NOT NULL , 
     cruise_cost_per_person NUMBER (7,2) , 
     ship_code              NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Unique identifier for cruise ' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Name of the Cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Description of the cruise ' 
;

COMMENT ON COLUMN CRUISE.cruise_date_time IS 'Date and time at which the particular cruise departs' 
;

COMMENT ON COLUMN CRUISE.cruise_cost_per_person IS 'cost each passenger has to pay for the cruise' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'Unique identifier for the ship ' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE ITINERARY 
    ( 
     date_time DATE  NOT NULL , 
     dep_arr   CHAR (1)  NOT NULL , 
     cruise_id NUMBER (7)  NOT NULL , 
     port_code CHAR (5)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT "chk_dep/arr" 
    CHECK (dep_arr IN ('A', 'D')) 
;

COMMENT ON COLUMN ITINERARY.date_time IS 'date and time of depature or arrival of cruise' 
;

COMMENT ON COLUMN ITINERARY.dep_arr IS 'Represents whether the cruise is arriving or departing at a specific date and time(D for Depart and A for Arrive' 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'Unique identifier for cruise ' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'Unique Identifier for port ' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_PK PRIMARY KEY ( date_time, cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     mani_no         NUMBER (7)  NOT NULL , 
     board_date_time DATE  NOT NULL , 
     cruise_id       NUMBER (7)  NOT NULL , 
     cabin_num       NUMBER (7)  NOT NULL , 
     ship_code       NUMBER (7)  NOT NULL , 
     pass_id         NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.mani_no IS 'Unique identifier for the manifest' 
;

COMMENT ON COLUMN MANIFEST.board_date_time IS 'The date and time at which the passenger first boarded the ship' 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'Unique identifier for cruise ' 
;

COMMENT ON COLUMN MANIFEST.cabin_num IS 'Unique Identifier for the Cabin ' 
;

COMMENT ON COLUMN MANIFEST.ship_code IS 'Unique identifier for the ship ' 
;

COMMENT ON COLUMN MANIFEST.pass_id IS 'Unique identifier for the passenger' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( mani_no ) ;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_NK UNIQUE ( cruise_id , pass_id , board_date_time ) ;

CREATE TABLE OPERATOR 
    ( 
     oper_id   NUMBER (7)  NOT NULL , 
     oper_comp VARCHAR2 (50)  NOT NULL , 
     oper_ceo  VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.oper_id IS 'Unique identifier for the operator ' 
;

COMMENT ON COLUMN OPERATOR.oper_comp IS 'Operator company name' 
;

COMMENT ON COLUMN OPERATOR.oper_ceo IS 'Name of the CEO of operator company ' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( oper_id ) ;

CREATE TABLE PASSENGER 
    ( 
     pass_id     NUMBER (7)  NOT NULL , 
     pass_fname  VARCHAR2 (50)  NOT NULL , 
     pass_lname  VARCHAR2 (50)  NOT NULL , 
     pass_gender VARCHAR2 (50)  NOT NULL , 
     pass_dob    DATE  NOT NULL , 
     guard_id    NUMBER (7)  NOT NULL , 
     add_num     NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER.pass_id IS 'Unique identifier for the passenger' 
;

COMMENT ON COLUMN PASSENGER.pass_fname IS 'The first name of the passenger ' 
;

COMMENT ON COLUMN PASSENGER.pass_lname IS 'the last name of the passenger ' 
;

COMMENT ON COLUMN PASSENGER.pass_gender IS 'The gender of the passenger' 
;

COMMENT ON COLUMN PASSENGER.pass_dob IS 'The date of birth of the passenger ' 
;

COMMENT ON COLUMN PASSENGER.guard_id IS 'Unique identifier for the passenger' 
;

COMMENT ON COLUMN PASSENGER.add_num IS 'unique identifier for the address (surrogate key)' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( pass_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      CHAR (5)  NOT NULL , 
     port_name      VARCHAR2 (50)  NOT NULL , 
     port_latitude  NUMBER (10,6)  NOT NULL , 
     port_longitude NUMBER (10,6) , 
     country_code   CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'Unique Identifier for port ' 
;

COMMENT ON COLUMN PORT.port_name IS 'the name of the port' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'latitude of the port ' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'the longitude of the port ' 
;

COMMENT ON COLUMN PORT.country_code IS 'Unique identifier for the country ' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code     NUMBER (7)  NOT NULL , 
     ship_name     VARCHAR2 (50)  NOT NULL , 
     ship_date     DATE  NOT NULL , 
     ship_tonnage  NUMBER (7,2)  NOT NULL , 
     ship_capacity NUMBER (10)  NOT NULL , 
     ship_country  VARCHAR2 (50)  NOT NULL , 
     oper_id       NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'Unique identifier for the ship ' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Name of the ship ' 
;

COMMENT ON COLUMN SHIP.ship_date IS 'Date at which the ship was commisioned ' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'the tonnage of the ship ' 
;

COMMENT ON COLUMN SHIP.ship_capacity IS 'the maximum capacity of the ship ' 
;

COMMENT ON COLUMN SHIP.ship_country IS 'country where the ship was registered ' 
;

COMMENT ON COLUMN SHIP.oper_id IS 'Unique identifier for the operator ' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT add_pass_fk FOREIGN KEY 
    ( 
     add_num
    ) 
    REFERENCES ADDRESS 
    ( 
     add_num
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cabin_mani_fk FOREIGN KEY 
    ( 
     cabin_num,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_num,
     ship_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT cruise_itin_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_mani_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT oper_ship_fk FOREIGN KEY 
    ( 
     oper_id
    ) 
    REFERENCES OPERATOR 
    ( 
     oper_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT pass_guard_fk FOREIGN KEY 
    ( 
     guard_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pass_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT pass_mani_fk FOREIGN KEY 
    ( 
     pass_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pass_id
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT port_count_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT port_itin_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

spool OFF
set echo OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
